apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: grab
data:
  POSTGRES_DB: "grab_db"
  SPRING_PROFILES_ACTIVE: "docker"
  KAFKA_BOOTSTRAP_SERVERS: "kafka-service:9092"
  REDIS_HOST: "redis-service"
  JWT_EXPIRATION_MS: "900000"
  JWT_REFRESH_EXPIRATION_MS: "604800000"
