name: grab_delivery
description: Smart Delivery App — Grab-like

publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.3.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  # State Management
  flutter_bloc: ^8.1.5
  equatable: ^2.0.5

  # Navigation
  go_router: ^13.2.0

  # HTTP & API
  dio: ^5.4.3
  retrofit: ^4.1.0

  # Local Storage
  flutter_secure_storage: ^9.0.0
  shared_preferences: ^2.2.3

  # Maps & Location
  google_maps_flutter: ^2.6.1
  geolocator: ^11.0.0
  geocoding: ^3.0.0

  # WebSocket (real-time tracking)
  web_socket_channel: ^2.4.5

  # UI Components
  flutter_svg: ^2.0.10
  cached_network_image: ^3.3.1
  shimmer: ^3.0.0
  lottie: ^3.1.0

  # Notifications
  firebase_core: ^2.31.0
  firebase_messaging: ^14.9.2
  flutter_local_notifications: ^17.1.2

  # Utils
  intl: ^0.19.0
  logger: ^2.3.0
  json_annotation: ^4.9.0
  freezed_annotation: ^2.4.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0
  build_runner: ^2.4.9
  json_serializable: ^6.8.0
  freezed: ^2.5.2
  retrofit_generator: ^8.1.0
  mockito: ^5.4.4

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/icons/
    - assets/animations/
